'use strict';
let token = '';
const el = id => document.getElementById(id);
const note = text => { el('status').textContent = text; };
async function api(path, method = 'GET', body) {
 const response = await fetch(path, {method, headers: {Authorization: `Bearer ${token}`, 'Content-Type': 'application/json'}, ...(body ? {body: JSON.stringify(body)} : {})});
 const data = await response.json(); if (!response.ok) throw Error(typeof data.detail === 'string' ? data.detail : JSON.stringify(data.detail)); return data;
}
function text(tag, value, parent) { const node = document.createElement(tag); node.textContent = value; parent.append(node); return node; }
function action(parent, label, callback) {const button = text('button', label, parent); button.type = 'button'; button.onclick = async () => {button.disabled=true; try {await callback(); await refresh();} catch(e){note(e.message);} finally {button.disabled=false;}};}
async function refresh() {
 const data = await api('/v1/overview'); note(data.summary); el('tasks').replaceChildren(); el('decisions').replaceChildren();
 const selected = el('project').value; el('project').replaceChildren(); const all = text('option','Lintas proyek',el('project'));all.value='';
 for(const p of data.projects) {const option=text('option',p.id,el('project'));option.value=p.id;} el('project').value=selected;
 for(const d of data.decisions) {const card=text('article','',el('decisions')); text('h3',`#${d.id} · ${d.title}`,card);text('p',`${d.state} / ${d.risk_level} / ${d.category}`,card);text('p',d.situation,card);text('p',`Rekomendasi: ${d.recommendation}`,card);text('pre',JSON.stringify(d.options,null,2),card);text('p',`Evidence: ${JSON.stringify(d.evidence)}`,card);
 if(d.state==='open') for(const [answer,label] of [['approve','Setujui'],['reject','Tolak'],['ask','Tanya'],['defer','Tunda'],['request_changes','Minta revisi'],['delegate','Delegasi']]) action(card,label,async()=>{let reason=prompt('Alasan / pertanyaan (wajib untuk revisi/delegasi)') || '';let delegate_to; if(answer==='delegate'){delegate_to=Number(prompt('ID operator terdaftar'));if(!delegate_to)return;}await api(`/v1/decisions/${d.id}/action`,'POST',{answer,reason,...(delegate_to?{delegate_to}:{})});});}
 for(const t of data.tasks) {const card=text('article','',el('tasks'));text('h3',`#${t.id} · ${t.status} · ${t.project || 'Lintas proyek'}`,card);text('p',t.requirement,card);text('p',t.last_message || '',card);action(card,'Lihat evidence',async()=>{const evidence=await api(`/v1/tasks/${t.id}/evidence`);text('pre',JSON.stringify(evidence,null,2),card);}); if(t.status==='waiting_input') action(card,'Jawab klarifikasi',async()=>{const message=prompt(t.last_message);if(message)await api('/v1/chat','POST',{message:`jawab tujuan #${t.id}: ${message}`,idempotency_key:crypto.randomUUID()});});}
 el('proposals').replaceChildren();for(const proposal of await api('/v1/improvement-proposals')){const card=text('article','',el('proposals'));text('h3',`#${proposal.id} · ${proposal.status}`,card);text('p',proposal.brief.problem,card);text('p',`Hypothesis: ${proposal.brief.hypothesis}; risk: ${proposal.brief.risk}`,card);text('p',`Test plan: ${proposal.brief.test_plan.join('; ')}`,card);text('p',`Evidence: ${proposal.brief.evidence.join('; ')}; rollback: ${proposal.brief.rollback_plan}`,card);if(!proposal.task_id)action(card,'Mulai proposal dengan approval gate',()=>api(`/v1/improvement-proposals/${proposal.id}/start`,'POST',{}));}
 el('metrics').textContent=JSON.stringify(await api('/v1/metrics'),null,2);el('conflicts').replaceChildren();for(const conflict of await api('/v1/memory/conflicts')){const card=text('article','',el('conflicts'));text('h3',`Konflik #${conflict.id} / memory:${conflict.memory_id}`,card);text('p',`${conflict.proposed_value} · Source: ${conflict.source}`,card);action(card,'Pilih nilai yang benar',async()=>{const value=prompt('Nilai final',conflict.proposed_value);const source=prompt('Source keputusan');if(value&&source)await api(`/v1/memory/${conflict.memory_id}/correction`,'POST',{value,source});});}
}
el('connect').onsubmit=async event=>{event.preventDefault();token=el('token').value;el('token').value='';try{await refresh();}catch(e){note(e.message);}};
el('chat').onsubmit=async event=>{event.preventDefault();try{const result=await api('/v1/chat','POST',{message:el('message').value,project:el('project').value,idempotency_key:crypto.randomUUID()});el('message').value='';await refresh();note(result.summary);}catch(e){note(e.message);}};
el('memory').onsubmit=async event=>{event.preventDefault();try{const result=await api(`/v1/memory/search?keys=${encodeURIComponent(el('query').value)}&role=lead`);el('knowledge').replaceChildren();for(const item of result.items){const card=text('article','',el('knowledge'));text('h3',`${item.key} · v${item.version} · ${item.label}`,card);text('p',item.value,card);text('p',`Source: ${item.source}; evidence: ${item.evidence_ref}; confidence: ${item.confidence}`,card);action(card,'Koreksi',async()=>{const value=prompt('Nilai pengganti',item.value);const source=prompt('Source koreksi');if(value&&source)await api(`/v1/memory/${item.id}/correction`,'POST',{value,source});});action(card,'Lock',async()=>{const reason=prompt('Alasan lock');if(reason)await api(`/v1/memory/${item.id}/lock`,'POST',{reason});});action(card,'Retract',async()=>{const reason=prompt('Alasan retract');if(reason)await api(`/v1/memory/${item.id}/retract`,'POST',{reason});});}}catch(e){note(e.message);}};
setInterval(()=>{if(token)refresh().catch(e=>note(e.message));},15000);

el('write-memory').onsubmit=async event=>{event.preventDefault();try{await api('/v1/memory','POST',{key:el('memory-key').value,value:el('memory-value').value,source:el('memory-source').value,scope:el('memory-scope').value});await refresh();note('Knowledge tersimpan dengan provenance.');}catch(e){note(e.message);await refresh().catch(()=>{});}};
